[ADD]초기 세팅
wecode-bootcamp-korea/43-2nd-Wevre-backend pull request #1
Opened 2023-03-24 10:00 UTC by soohyunkim5

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 초기 세팅
-
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- dev 브랜치를 생성해서 초기 세팅 완료.

<br />

## :: 테스트 결과 이미지
![image](https://user-images.githubusercontent.com/110106750/227490415-ce9dc21c-863e-4e02-aa8e-a993135e964c.png)

2023-03-25 07:08 UTC, Kang-kyunghun requested changes

2023-03-25 07:08 UTC, Kang-kyunghun commented on api/utils/error.js
> +/*
해당 파일의 들여씌기 간격이 다른 파일의 코드들과 맞지 않습니다. 확인해 주세요.

2023-03-25 07:08 UTC, Kang-kyunghun commented on api/utils/error.js
> +module.exports = { catchAsync, globalErrorHandler }
- 들여씌기 간격 확인해 주세요.
- 코드들 사이에 간격은 굳이 없어도 될 것 같습니다.
```suggestion
	console.error(err.stack)
	
	err.statusCode = err.statusCode || 500;
	res.status(err.statusCode).json({ message: err.message })
}

module.exports = { catchAsync, globalErrorHandler }
```

2023-03-27 07:21 UTC, Jon9Beom commented on .env.sample
> +DATABASE_URL : "rdbms://username:userpassword@local_host:db_port/database_name"
```suggestion
DATABASE_URL = "rdbms://username:userpassword@local_host:db_port/database_name"
```

2023-03-27 07:21 UTC, Jon9Beom commented on api/models/dataSource.js
> +  type: "mysql",
```suggestion
  type: process.env.DB_CONNECTION,
```
`"mysql"`이라고 하드코딩 하지않고, `.env`속의 환경변수를 활용해주세요~

2023-03-27 07:39 UTC, Jon9Beom commented
`.env.sample`에 남겨드린 코멘트 반영해주세요! 추가로 여러개로 올라와있는 커밋들 리베이스 활용해서 하나로 squash 한 뒤 push 해주세요.

2023-03-28 01:17 UTC, Jon9Beom commented
LGTM 👍

2023-03-28 01:17 UTC, merged